name: Build and Test
on: [ push ]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      actions: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: oracle
          cache: maven
      - name: Run build with Maven
        run: mvn --batch-mode -DskipTests package
      - name: Run unit tests and integration tests
        run: mvn --batch-mode test
#      - name: Display test results
#        uses: dorny/test-reporter@v1
#        if: success() || failure()
#        with:
#          name: Unit Tests results
#          path: target/surefire-reports/*.xml
#          reporter: java-junit

